### ISSUE TITLE
Healed locators are displayed twice on the report

### ISSUE THREAD

**Issue by nareshm1** [healenium/healenium-report-mvn#3]
@GannaChernyshova 
I report the each healed locators  are displayed twice

![image](https://user-images.githubusercontent.com/67036539/100022638-8d970480-2e09-11eb-895a-3e8eabdf84c1.png)

Report link :http://localhost:7878/healenium/report/e2b9a194-332e-4b38-9949-8e60d9809b62

**Comment by GannaChernyshova** [comment]
It's an expected behaviour. Will be updated on implementation of https://github.com/healenium/healenium-web/issues/28
